/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Chris
 */
public class CCTV extends javax.swing.JFrame {

    /**
     * Creates new form CCTV
     */
    public CCTV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_video = new javax.swing.JPanel();
        l_barraEstado = new javax.swing.JLabel();
        b_salir = new javax.swing.JButton();
        b_desactivar = new javax.swing.JButton();
        b_activar = new javax.swing.JButton();
        mb = new javax.swing.JMenuBar();
        m_archivo = new javax.swing.JMenu();
        mi_activar = new javax.swing.JMenuItem();
        mi_desactivar = new javax.swing.JMenuItem();
        mi_salir = new javax.swing.JMenuItem();
        m_configuracion = new javax.swing.JMenu();
        mi_rusuario = new javax.swing.JMenuItem();
        mi_rescenario = new javax.swing.JMenuItem();
        mi_eusuario = new javax.swing.JMenuItem();
        mi_eescenario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_video.setPreferredSize(new java.awt.Dimension(540, 320));

        javax.swing.GroupLayout p_videoLayout = new javax.swing.GroupLayout(p_video);
        p_video.setLayout(p_videoLayout);
        p_videoLayout.setHorizontalGroup(
            p_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p_videoLayout.setVerticalGroup(
            p_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        l_barraEstado.setText("Estado:");

        b_salir.setText("Salir");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        b_desactivar.setText("Desactivar");

        b_activar.setText("Activar");

        m_archivo.setText("Archivo");

        mi_activar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mi_activar.setText("Activar");
        m_archivo.add(mi_activar);

        mi_desactivar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mi_desactivar.setText("Desactivar");
        m_archivo.add(mi_desactivar);

        mi_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mi_salir.setText("Salir");
        mi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_salirActionPerformed(evt);
            }
        });
        m_archivo.add(mi_salir);

        mb.add(m_archivo);

        m_configuracion.setText("Configuracion");

        mi_rusuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mi_rusuario.setText("Registrar Usuario");
        m_configuracion.add(mi_rusuario);

        mi_rescenario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mi_rescenario.setText("Registrar Escenario");
        m_configuracion.add(mi_rescenario);

        mi_eusuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mi_eusuario.setText("Eliminar Usuario");
        m_configuracion.add(mi_eusuario);

        mi_eescenario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mi_eescenario.setText("Eliminar Escenario");
        m_configuracion.add(mi_eescenario);

        mb.add(m_configuracion);

        setJMenuBar(mb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_video, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_barraEstado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 332, Short.MAX_VALUE)
                        .addComponent(b_activar)
                        .addGap(2, 2, 2)
                        .addComponent(b_desactivar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_barraEstado)
                        .addGap(31, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_activar)
                            .addComponent(b_desactivar)
                            .addComponent(b_salir))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_salirActionPerformed
        // TODO add your handling code here:
        try{
            System.exit(0);
        }catch(Exception e){
            System.err.print("Error en la salida del programa\n "+e.getMessage());
        }
    }//GEN-LAST:event_mi_salirActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        // TODO add your handling code here:
        try{
            System.exit(0);
        }catch(Exception e){
            System.err.print("Error en la salida del programa\n "+e.getMessage());
        }
    }//GEN-LAST:event_b_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CCTV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_activar;
    private javax.swing.JButton b_desactivar;
    private javax.swing.JButton b_salir;
    public static javax.swing.JLabel l_barraEstado;
    private javax.swing.JMenu m_archivo;
    private javax.swing.JMenu m_configuracion;
    private javax.swing.JMenuBar mb;
    public static javax.swing.JMenuItem mi_activar;
    public static javax.swing.JMenuItem mi_desactivar;
    public static javax.swing.JMenuItem mi_eescenario;
    public static javax.swing.JMenuItem mi_eusuario;
    public static javax.swing.JMenuItem mi_rescenario;
    public static javax.swing.JMenuItem mi_rusuario;
    private javax.swing.JMenuItem mi_salir;
    private javax.swing.JPanel p_video;
    // End of variables declaration//GEN-END:variables
}
